#!/usr/bin/env php
<?php
/*
 * #! - это shebang скрипт выполняется как программа в unix-подобных ОС
 * #!/usr/bin/env php - выполнить файл как программу php
 * /usr/bin/env - UNIX-утилита, исполняющая команду с изменением окружения
 */

if (PHP_SAPI !== 'cli') {
    exit(1);
}

var_dump($argv);